version: '3.8'

services:
  # Banco de Dados PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: sus_postgres
    environment:
      POSTGRES_USER: sus_user
      POSTGRES_PASSWORD: sus_password
      POSTGRES_DB: sus_triage_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sus-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sus_user -d sus_triage_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Mensageria RabbitMQ (Com Painel de Gestão na porta 15672)
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: sus_rabbitmq
    ports:
      - "5672:5672"   # Porta para aplicação Java
      - "15672:15672" # Painel Web (Login: guest/guest)
    networks:
      - sus-network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  # Cache Redis
  redis:
    image: redis:7-alpine
    container_name: sus_redis
    ports:
      - "6379:6379"
    networks:
      - sus-network
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  rabbitmq_data:
  redis_data:

networks:
  sus-network:
    driver: bridge