spring:
  application:
    name: sus-triage-api

  # Configuração do Banco de Dados (PostgreSQL)
  datasource:
    url: jdbc:postgresql://localhost:5432/sus_triage_db
    username: sus_user
    password: sus_password
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      platform: postgresql
      mode: always # Executa o schema-h2.sql e data-h2.sql sempre que subir

  jpa:
    hibernate:
      ddl-auto: none # 'none' para não conflitar com o schema-h2.sql
    show-sql: true
    defer-datasource-initialization: true # Espera o Hibernate validar para rodar os dados
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Configuração do RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  # Configuração do Redis
  data:
    redis:
      host: localhost
      port: 6379

# Configuração do Swagger
springdoc:
  swagger-ui:
    path: /swagger-ui.html