spring:
  application:
    name: sus-triage-api

  # Configuração do Banco de Dados
  datasource:
    url: jdbc:postgresql://localhost:5432/sus_triage_db
    username: sus_user
    password: sus_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Cria as tabelas sozinho (bom para dev/mvp)
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Configuração do RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  # Configuração do Redis
  data:
    redis:
      host: localhost
      port: 6379

# SpringDoc OpenAPI configuration
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true